network:
  version: 2
  ethernets:

    ens18:
      dhcp4: false

    ens19:
      dhcp4: false

    ens20:
      dhcp4: false

    ens21:
      dhcp4: false

    ens22:
      dhcp4: false

  bridges:

    br-int:
      interfaces: [ens18]
      dhcp4: false
      addresses: [192.168.100.151/24]
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.100.1
      parameters:
        stp: false
        forward-delay: 0

    br-ksa:
      interfaces: [ens19]
      dhcp4: false
      addresses: []
      parameters:
        stp: false
        forward-delay: 0
      dhcp6: false
      accept-ra: false
      link-local: []

    br-uae:
      interfaces: [ens20]
      dhcp4: false
      addresses: []
      parameters:
        stp: false
        forward-delay: 0
      dhcp6: false
      accept-ra: false
      link-local: []

    br-pak:
      interfaces: [ens21]
      dhcp4: false
      addresses: []
      parameters:
        stp: false
        forward-delay: 0
      dhcp6: false
      accept-ra: false
      link-local: []

    br-usa:
      interfaces: [ens22]
      dhcp4: false
      addresses: []
      parameters:
        stp: false
        forward-delay: 0
      dhcp6: false
      accept-ra: false
      link-local: []